# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-29 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=124, null=True)),
                ('Phone', models.IntegerField()),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
    ]
